apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: b9od7exha-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/b9od7exha-java-springboot-gitops